const TechStack = [
  {
    title: "VS Code",
    id: 0,
    main: "zt3zhcqe7gx714aohzp9",
    desc: "Best coding IDE to ever exist, comes with tons of customization",
    tag: "code",
    bg: "bg-blue-50",
    text: "text-blue-500",
  },
  {
    title: "JavaScript",
    id: 1,
    main: "ymrzp54b0busy5h5wlgh",
    desc: "A lightweight, interpreted, or just-in-time compiled programming language with first-class functions.",
    tag: "code",
    bg: "bg-yellow-50",
    text: "text-yellow-500",
  },
  {
    title: "TypeScript",
    id: 2,
    main: "w2bdbdblh7uw9k0atzx1",
    desc: "SuperScript of Javascript, made by microsoft with robust type safety.",
    tag: "code",
    bg: "bg-blue-50",
    text: "text-blue-500",
  },
  {
    title: "React JS",
    id: 3,
    main: "fxolheffuslp1a8f0j0p",
    desc: "A free and open-source front-end JavaScript library for building user interfaces based on components",
    tag: "develop",
    bg: "bg-blue-50",
    text: "text-blue-500",
  },
  {
    title: "Node.js",
    id: 4,
    main: "lxhgd2emm2pn7cyuq7pd",
    desc: "A JavaScript runtime built on Chrome's V8 engine for executing JavaScript code outside of a browser.",
    tag: "develop",
    bg: "bg-gray-900",
    text: "text-gray-50",
  },
  {
    title: "Tailwind CSS",
    id: 5,
    main: "pmau3xqzddpe3hlwmxtp",
    desc: "A utility-first CSS framework for rapidly building modern websites without ever leaving your HTML.",
    tag: "design",
    bg: "bg-green-50",
    text: "text-green-500",
  },
  {
    title: "Redux.js",
    id: 6,
    main: "s94jajxu518f61fsuhfe",
    desc: "A predictable state management library that helps manage the application's state in a single, centralized store.",
    tag: "develop",
    bg: "bg-indigo-50",
    text: "text-indigo-500",
  },
  {
    title: "GitHub",
    id: 7,
    main: "zva5tmqwrx2uly42wdrq",
    desc: "A developer's go-to platform for collaborating and showcasing their code.",
    tag: "platform",
    bg: "bg-gray-900",
    text: "text-gray-100",
  },
  {
    title: "Brave",
    id: 8,
    main: "awtbag8ce9hhhls53b5k",
    desc: "A privacy focused browser used to block ads and extra pops.",
    tag: "platform",
    bg: "bg-orange-500",
    text: "text-orange-100",
  },
];

export default TechStack